### Send POST request with json body
POST {{host}}/user/login
Content-Type: application/json

{
  "nickName":"menglong",
  "password":"menglong",
  "account": "menglong0",
  "email": "menglong",
  "id": 0

}
> {%
client.assert(typeof response.body.data.token !== "undefined", "No token returned");
client.global.set("auth_token", response.body.data.token);
%}
###
PUT {{host}}/user/register
Content-Type: application/json

{
  "nickName":"menglong",
  "password":"menglong",
  "account": "menglong0",
  "email": "menglong",
  "id": 0
}
> {%
client.assert(typeof response.body.data.token !== "undefined", "No token returned");
client.global.set("auth_token", response.body.data.token);
%}
###
###  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoibWVuZ2xvbmcwbWVuZ2xvbmcifQ.7qaW1xVjo6A4gpqCm41s7jK_HYTpZRo_mT_O9Vl6NTA
DELETE {{host}}/user/delete/1
Authorization: Bearer {{auth_token1}}

###


